### ISSUE TITLE
Feature request: supporting older Python versions

### ISSUE THREAD

**Issue by m-aciek** [glyph/DateType#6]
Thank you for sharing this library! Would it be costly to support Python 3.7+? (Currently declared Python support is for 3.10+.) I think I would be willing to create a PR.

Notes:
* [typing.Protocol](https://docs.python.org/3/library/typing.html?#typing.Protocol) was added in 3.8, to have the support we should use [typing extensions](https://pypi.org/project/typing-extensions/)
* [union operator for types is supported Python 3.10](https://peps.python.org/pep-0604/), so `|` should be converted to `Union`s and `| None` should be converted to `Optional`s for now

**Comment by glyph** [comment]
Sure, I'd be happy to look at this.
